name: CI

on: [push]

jobs:
  minitest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1

      - name: Set up gems cache
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ruby-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ruby-

      - name: Install Ruby dependencies
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Run tests
        run: bundle exec rake
